### ISSUE TITLE
Upload cargo.lock

### ISSUE THREAD

**Issue by Cryolitia** [KaiserY/mdbook-typst-pdf#4]
https://course.rs/cargo/guide/cargo-toml-lock.html#%E6%98%AF%E5%90%A6%E4%B8%8A%E4%BC%A0%E6%9C%AC%E5%9C%B0%E7%9A%84-cargolock

It's necessary for packaging in Nix https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md?plain=1#L87

**Comment by KaiserY** [comment]
done in v0.4.0
